version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=scrapy_u
      - PGUSER=postgres
      - POSTGRES_PASSWORD=scrapy_p
      - POSTGRES_DB=sreality_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "sreality_db"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 40s  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  scrapy:
    build: ./sreality
    volumes:
      - ./sreality:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  web: 
    build: ./flask_app
    volumes:
      - ./flask_app:/usr/src/app
    ports: 
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy