version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    env_file:
      - db-variables.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 40s  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  scrapy:
    build: ./sreality
    volumes:
      - ./sreality:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - db-variables.env
    depends_on:
      db:
        condition: service_healthy

  web: 
    build: ./flask_app
    volumes:
      - ./flask_app:/usr/src/app
    ports: 
      - '8080:8080'
    env_file:
      - db-variables.env
    depends_on:
      db:
        condition: service_healthy